### ISSUE TITLE
Looking to use this SDK as a starting point to code something like this?

### ISSUE THREAD

**Issue by ErikHR** [kriasoft/TDAmeritrade#1]
I have downloaded your app and have a simple test harness working to make sure it works for me.

code:

static void Main(string[] args) {
            var client = new TDAClient();
            client.LogIn("abc", "123");
            var accountName = client.User.Account.DisplayName;
            client.LogOut();
}

I currently use ThinkORSwim's ThinkBack tool to backtest my options strategies, but it is very tedious entering trades for a few years back to see how they would have performed.

I am a Sr. Software engineer.  I have been coding C# since V1.  I would like to be able to create a backtest for an options strategy as oposed to manually entering option trades into the ThinkBack tool.  Is this something I can use your code as a starting place achive?  I do not have access to apiforums.tdameritrade.com yet, but I stumbled accross your software and decided to see what it is used for.

Thanks,
Erik

**Comment by koistya** [comment]
Yeah, you're free to use it. It could be good as a starting point or sample
how to work with TDA web services..

On Fri, Dec 30, 2011 at 12:24 PM, ErikHR <
reply@reply.github.com

**Comment by ErikHR** [comment]
Do you know where the TDA web services API is documented?

-----Original Message-----

**Comment by koistya** [comment]
Here it is: http://apiforums.tdameritrade.com/
